abstract final class ApiConstants {
  static const baseUrl = 'https://app.kilo.ai';
  static const wsUrl = 'wss://ingest.kilosessions.ai/api/user/web';
  static const getToken = '/api/trpc/activeSessions.getToken';
  static const listActiveSessions = '/api/trpc/activeSessions.list';
  static const getSessionMessages = '/api/trpc/cliSessionsV2.getSessionMessages';
  static const openRouterModels = '/api/openrouter/models';
  static const deviceAuthCodes = '/api/device-auth/codes';
  static const profileUsage = '/api/profile/usage';
  static const profileBalance = '/api/profile/balance';
  static const profileMe = '/api/profile';
  static const byokList = '/api/trpc/byok.list';
  static const byokCreate = '/api/trpc/byok.create';
  static const byokUpdate = '/api/trpc/byok.update';
  static const byokDelete = '/api/trpc/byok.delete';
  static const byokSetEnabled = '/api/trpc/byok.setEnabled';
  static const byokTestApiKey = '/api/trpc/byok.testApiKey';
  static const byokSupportedModels = '/api/trpc/byok.listSupportedModels';
}
